### ISSUE TITLE
你的文件被病毒感染了

### ISSUE THREAD

**Issue by laputae** [huyinhao/hyh-in-hdu#2]
我在下载完你提供的文件之后，Windows defender弹出病毒提示，
这里有一个知乎上的关于GitHub传播病毒的文章
[https://zhuanlan.zhihu.com/p/338851709](url)

**Comment by huyinhao** [comment]
能更具体一些吗，我下载完并没有发现病毒报告

**Comment by laputae** [comment]
我5月份使用edge浏览器下载压缩包会提示无法下载。现在我又试了一下，系统没有报告病毒
